(dolist (prf '(actual built-in craft devel))
  (let ((fname (cfg/path (format "init/init-%S.el" prf))))
    ;; (send-string-to-terminal (format "compile profile %s" prf))
    (message "Compile: %s" fname)
    (when (file-exists-p fname)
      (byte-compile-file fname))
    ))
