#!/bin/sh

alias tmax='emax -nw'
alias emaxb='env EMAX_PRF=built-in emax'
alias emaxc='env EMAX_PRF=craft emax'
alias emaxd='env EMAX_PRF=devel emax'
alias tmaxb='emaxb -nw'
alias tmaxc='emaxc -nw'
alias tmaxd='emaxd -nw'

alias emacs-q='emacs -q --init-dir="~/.config/emacs/target/emacs-q"'
